version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/storybook"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/lib"
    schedule:
      interval: "daily"
