version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd lib
      - npm install
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install

  build:
    commands:
      - npx tsc && npx vite build --mode production

  post_build:
    commands:
      - aws s3 sync ./dist s3://aktopia-elements --delete

artifacts:
  files:
    - '**/*'
  discard-paths: false
  base-directory: 'lib/dist'