version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd lib
      - npm install
  build:
    commands:
      - npx tsc && npx vite build --mode production
  post_build:
    commands:
      - >-
        aws s3 sync ./dist s3://aktopia-elements --delete
        --metadata="surrogate-key=${SURROGATE_KEY}"
      - >-
        curl -i -X POST "https://api.fastly.com/service/${FASTLY_SERVICE_ID}/purge/${SURROGATE_KEY}" 
        -H "Fastly-Key: ${FASTLY_API_KEY}"
        -H "Accept: application/json"
