name: "Chromatic"

on: push

jobs:
  chromatic:
    environment: elements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: /storybook
          buildScriptName: build
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          zip: true